### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by tianon**
cc @ehazlett @nathanleclaire @jeffdm @mchiang0610

Not ready for merge just yet, but should be prepped for the 1.8.0 release.

### CODE REVIEW

**Comment by tianon** [comment]
See also https://github.com/boot2docker/boot2docker/pull/1013.

**Comment by nathanleclaire** [comment]
LGTM

**Comment by ehazlett** [comment]
LGTM

**Comment by SvenDowideit** [comment]
LGTM, though I'd prefer to also have a proposed EOL date

**Comment by josephpage** [comment]
Docker 1.8.0 was released :smile:

**Comment by nathanleclaire** [comment]
Seems OK to merge this in now

**Comment by tianon** [comment]
:+1:

**Pull request merged**
